spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.vertyll.projecta.*"
        spring.json.value.default.type: "com.vertyll.projecta.sharedinfrastructure.event.DomainEvent"
        spring.json.use.type.headers: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.value.default.type: "com.vertyll.projecta.sharedinfrastructure.event.DomainEvent"

projecta:
  shared:
    security:
      jwt:
        secret-key: CbIKeXKAkneVUn5me1nHZ+V74qpmZ36InUDFEXsg6YY=
        access-token-expiration: 900000  # 15 minutes in milliseconds
        refresh-token-expiration: 604800000  # 7 days in milliseconds
        refresh-token-cookie-name: refresh_token
        auth-header-name: Authorization
        cookie:
          httpOnly: true
          secure: false
          sameSite: Strict
          path: "/"
    services:
      auth-service:
        url: http://localhost:8082
      user-service:
        url: http://localhost:8083
      role-service:
        url: http://localhost:8084
      mail-service:
        url: http://localhost:8085
      topics:
        # Topics that services publish to or subscribe from
        all:
          user-registered: "user-registered"
          user-activated: "user-activated"
          user-password-reset: "user-password-reset"
          credentials-verification: "credentials-verification"
          credentials-verification-result: "credentials-verification-result"
          user-updated: "user-updated"
          user-email-updated: "user-email-updated"
          user-password-updated: "user-password-updated"
          user-deleted: "user-deleted"
          user-deletion: "user-deletion"
          user-creation-confirmed: "user-creation-confirmed"
          role-created: "role-created"
          role-updated: "role-updated"
          role-deleted: "role-deleted"
          role-assigned: "role-assigned"
          role-revoked: "role-revoked"
          mail-requested: "mail-requested"
          mail-sent: "mail-sent"
          mail-failed: "mail-failed"
          saga-compensation: "saga-compensation"

