projecta:
  shared:
    security:
      jwt:
        secret-key: CbIKeXKAkneVUn5me1nHZ+V74qpmZ36InUDFEXsg6YY=
        access-token-expiration: 900000  # 15 minutes in milliseconds
        refresh-token-expiration: 604800000  # 7 days in milliseconds
        refresh-token-cookie-name: refresh_token
        auth-header-name: Authorization
        cookie:
          httpOnly: true
          secure: false
          sameSite: Strict
          path: "/"
    services:
      auth-service:
        url: http://localhost:8082
      user-service:
        url: http://localhost:8083
      role-service:
        url: http://localhost:8084
      mail-service:
        url: http://localhost:8085
        
# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /api-docs
    config-url: /api-docs/swagger-config

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      access: read-only
    prometheus:
      access: read-only
