projecta:
  shared:
    security:
      jwt:
        secret-key: CbIKeXKAkneVUn5me1nHZ+V74qpmZ36InUDFEXsg6YY=
        access-token-expiration: 900000  # 15 minutes in milliseconds
        refresh-token-expiration: 604800000  # 7 days in milliseconds
        refresh-token-cookie-name: refresh_token
        auth-header-name: Authorization
    services:
      auth-service:
        url: http://localhost:8082
      user-service:
        url: http://localhost:8083
      role-service:
        url: http://localhost:8084
      mail-service:
        url: http://localhost:8085

# Import the Kafka topics configuration
spring:
  config:
    import: classpath:kafka-topics.yml

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.value.default.type: "com.vertyll.projecta.sharedinfrastructure.event.DomainEvent"
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.vertyll.projecta.*"
        spring.json.value.default.type: "com.vertyll.projecta.sharedinfrastructure.event.DomainEvent"
        spring.json.use.type.headers: true
        
# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /api-docs
    config-url: /api-docs/swagger-config

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      access: read-only
    prometheus:
      access: read-only
